### ISSUE TITLE
Clicking on the tools does not work in Safari

### ISSUE THREAD

**Issue by hairydalek** [rawles/teletext-editor#55] opened 2016-10-10 10:53 UTC
In Firefox on a Mac, I can insert control codes from the list on the left by clicking on them.

Is Safari on a Mac, I can’t. Those clicks do not work.

**Comment by dodginess** [comment] 2016-10-10 13:55
This has something to do with Safari not creating the KeyboardEvent object correctly - what the code is trying to do at that point is simulate a key press based on whatever button you just clicked on. The solution might be to put that code in a try/catch block and use a deprecated method of capturing the keydown event if an exception is generated.

**Comment by rawles** [comment] 2016-10-30 19:27
Yes, this sort of thing is certainly browser-specific behaviour and I've had other people say that similar things don't work for them. 

This might help:

http://stackoverflow.com/questions/961532/firing-a-keyboard-event-in-javascript

**Comment by rawles** [comment] 2016-10-30 20:55
This is a duplicate of #44.

**Closed as completed** 2016-10-30 21:41 UTC
